name: joachimnaess
favicon: null
layout_spectrum: 0.22371
typography_spectrum: 0.49082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f8f7'
    - '#4e5566'
    - '#2d2a32'
    - '#b5c2c7'
    - '#6a7180'
  brandStrength: 0.75
  lightness: 0.23014472564682364
  saturation: 0.75
  rhythmicContrast: 0.826607109978795
purpose: []
