name: joachimnaess
favicon: null
layout_spectrum: 0.22371
typography_spectrum: 0.50083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefef'
    - '#010101'
    - '#506173'
    - '#9fabb7'
    - '#2c2825'
  brandStrength: 0.5625
  lightness: 0.23014472564682364
  saturation: 0.75
  rhythmicContrast: 0.826607109978795
purpose: []
